version: 2

models:
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_vendors
    columns:
      - name: vendor_id
        tests:
          - unique
          - not_null

  - name: dim_dates
    columns:
      - name: date
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fct_sales
    columns:
      - name: sales_key
        tests:
          - unique
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: order_date
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date
      - name: amount
        tests:
          - not_null